# Generated by Django 4.1 on 2022-08-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appartments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('operation_type', models.IntegerField()),
                ('district_name', models.CharField(max_length=255, null=True)),
                ('street_name', models.CharField(max_length=255, null=True)),
                ('square_meters', models.FloatField(null=True)),
                ('rooms_count', models.IntegerField(null=True)),
                ('floor', models.IntegerField(null=True)),
                ('total_price', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('photo', models.CharField(max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riarest.cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riarest.owners')),
            ],
        ),
    ]
