# Generated by Django 4.1 on 2022-08-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riarest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartments',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
